In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('titanic.csv')

In [12]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#Sibling accompying Passenger(SibSp)
#Parch means no of elders accompnying passenger
#Embark means port the ship left at

In [4]:
# The number of survived passengers as opposed to unsurvived
(df[df['Survived'] == 1]['Survived'].sum()/len(df['Survived']))*100

np.float64(38.38383838383838)

In [5]:
df['Survived'].value_counts(normalize=True)

Survived
0    0.616162
1    0.383838
Name: proportion, dtype: float64

In [8]:
# Of the number of survived, how many % are female
len(df[(df['Survived'] == 1) & (df['Sex']=='female')])/len(df)

0.2615039281705948

In [9]:
# The number of survived passenger in S 
(df[df['Embarked'] == 'S']['Survived'].sum()/len(df['Survived']))* 100

np.float64(24.354657687991022)

In [10]:
(df[df['Embarked'] == 'C']['Survived'].sum()/len(df['Survived']))* 100

np.float64(10.437710437710438)

In [11]:
(df[df['Embarked'] == 'Q']['Survived'].sum()/len(df['Survived']))* 100

np.float64(3.3670033670033668)

In [16]:
df[df['Sex']=='female']['Age'].mean()

np.float64(27.915708812260537)

In [17]:
df[df['Sex']=='male']['Age'].mean()

np.float64(30.72664459161148)

In [18]:
df.groupby('Sex')['Age'].mean()

Sex
female    27.915709
male      30.726645
Name: Age, dtype: float64

In [19]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    38.233441
2    29.877630
3    25.140620
Name: Age, dtype: float64

In [20]:
df[df['Pclass'] == 1].groupby('Sex')['Age'].mean()

Sex
female    34.611765
male      41.281386
Name: Age, dtype: float64

In [21]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [23]:
# Average fare per class
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [24]:
#Minimum fare
df['Fare'].min()

np.float64(0.0)

In [ ]:
#Maximum fare
df['Fare'].max()

np.float64(512.3292)

In [ ]:
#Average fare
df['Fare'].mean()

np.float64(32.204207968574636)

In [34]:
# If fare is upto 15, call it 'lower class'
# If fare is between 15 - 32, call it 'middle class'
# If fare is between 32 - 100, call it 'upper class'
# If fare is more than 100, call it 'elites'
df['Economic classes']=df.apply(lambda row:'lower class' if row['Fare'] <= 15 else 'middle class' if row['Fare']>=15 and row['Fare'] <= 32 else 'upper class' if row['Fare'] > 32 and row['Fare'] <= 100 else 'elites',axis=1)

In [35]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Economic classes
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,lower class
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,upper class
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,lower class
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,upper class
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,lower class

In [37]:
df['Economic classes'].value_counts()

Economic classes
lower class     458
middle class    222
upper class     158
elites           53
Name: count, dtype: int64

In [41]:
df[df['Economic classes'] != 'elites'].groupby('Economic classes')['Fare'].mean()

Economic classes
lower class      8.853647
middle class    23.860209
upper class     59.678931
Name: Fare, dtype: float64

In [42]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Economic classes
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,lower class
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,upper class
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,lower class
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,upper class
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,lower class

In [43]:
# Calculate average for every Embarked town
df.groupby('Embarked')['Fare'].mean()

Embarked
C    59.954144
Q    13.276030
S    27.079812
Name: Fare, dtype: float64

In [45]:
df.groupby(['Economic classes','Embarked'])['Age'].mean()

Economic classes  Embarked
elites            C           33.576923
                  S           30.041818
lower class       C           23.626286
                  Q           30.394737
                  S           29.188074
middle class      C           27.178571
                  Q           18.857143
                  S           28.939452
upper class       C           37.682927
                  Q           38.500000
                  S           30.966667
Name: Age, dtype: float64

In [50]:
# In each class find the count of people who survived and didn't survive
df.groupby(['Economic classes','Survived'])['PassengerId'].count()

Economic classes  Survived
elites            0            14
                  1            39
lower class       0           344
                  1           114
middle class      0           120
                  1           102
upper class       0            71
                  1            87
Name: PassengerId, dtype: int64

In [4]:
import pandas as pd
df = pd.read_csv('titanic.csv')
df.head()
#df.shape

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
#PROBLEMS:
# 1.Total people travelling
df['PassengerId'].count()

In [94]:
# 2.How many survived/died
df['Survived'].sum()
df[df['Survived'] == 0]['PassengerId'].count()

np.int64(549)

In [ ]:
# 3.a)How many elders were there?
df[df['Parch'] != 0]['Parch'].sum()

np.int64(340)

In [99]:
# 3. b) How many elders survived?
df['Elders Survived'] = df['Parch'] * df['Survived']

In [103]:
# 3. b) How many elders survived?
(df['Elders Survived'].sum()/df[df['Parch'] != 0]['Parch'].sum())*100

np.float64(46.76470588235294)

In [116]:
# 4.How many kids were there?
df[(df['Age'] < 18)]['PassengerId'].count()

np.int64(113)

In [114]:
#4.b)How many survived?
df[(df['Age'] < 18) & (df['Survived'] != 0)]['PassengerId'].count()

np.int64(61)

In [126]:
# 5. How many females were there?How many survived?
df[df['Sex'] == 'female'].count()
df[(df['Sex'] == 'female') & df['Survived'] != 0]['Survived'].sum()

np.int64(233)

In [ ]:
# 6.How many were rich and poor were there?How many survived?
# If fare is upto 15, call it 'lower class'
# If fare is between 15 - 32, call it 'middle class'
# If fare is between 32 - 100, call it 'upper class'
# If fare is more than 100, call it 'elites'
df['Economic classes']=df.apply(lambda row:'lower class' if row['Fare'] <= 15 else 'middle class' if row['Fare']>=15 and row['Fare'] <= 32 else 'upper class' if row['Fare'] > 32 and row['Fare'] <= 100 else 'elites',axis=1)
df.groupby('Economic classes')['Survived'].count()
df.groupby('Economic classes')['Survived'].sum()

Economic classes
elites           39
lower class     114
middle class    102
upper class      87
Name: Survived, dtype: int64

In [88]:
# 7.What's survival ratio of people boarding on each port?
(df[df['Survived'] == 1].groupby('Embarked')['Survived'].count()/df.shape[0])*100

Embarked
C    10.437710
Q     3.367003
S    24.354658
Name: Survived, dtype: float64

In [76]:
# 8.How many were travelling solo? What ratio of those survived? 
(df[(df['SibSp'] == 0) & (df['Parch'] == 0)]['Survived'].sum()/(df[(df['SibSp'] == 0) & (df['Parch'] == 0)].shape[0]))*100

np.float64(30.353817504655495)

In [121]:
# 9.a)How many were not travelling solo?
df_non_solo_travellers = df[(df['SibSp'] != 0)|(df['Parch'] != 0)]

In [120]:
# 9.a)How many were not travelling solo?
len(df_non_solo_travellers)

354

In [ ]:
#9. b)what ratio of those survived?
(df_non_solo_travellers['Survived'].sum()/(df_non_solo_travellers.shape[0]))*100

np.float64(50.56497175141242)

In [ ]:
# 10. Ratio of male and female travelling solo
df_female_solo = df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'female')]
df_male_solo = df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'male')]

In [ ]:
# 10. Ratio of male and female travelling solo
len(df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'female')])

In [ ]:
# 10. Ratio of male and female travelling solo

len(df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'male')])

411

In [ ]:
# 10. Ratio of male and female travelling solo

(len(df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'female')])/len(df[(df['SibSp'] == 0) & (df['Parch'] == 0) & (df['Sex'] == 'male')]))*100

30.656934306569344